- client/src/components/_common/header/Header.styles.ts
- client/src/components/_common/header/Header.tsx
- client/src/components/_common/navBar/NavBar.styles.ts
- client/src/components/_common/navBar/NavBar.tsx
- client/src/hooks/_common/useSwitch.ts
- client/src/styles/theme.ts
https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-56
PR 링크
https://github.com/woowacourse-teams/2023-co-kirikiri/pull/12
> [feat/CK-56] NavBar 뼈대 구현 PR 내용을 반영한다

- client/src/apis/axios/client.ts
- client/src/apis/goalRoom.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
- client/src/constants/goalRoom/recruitmentStatus.ts
- client/src/hooks/_common/useValidParams.ts
- client/src/hooks/queries/goalRoom.ts
- client/src/index.tsx
- client/src/mocks/fixtures/goalRoom.ts
- client/src/mocks/handlers/goalRoomHander.ts
- client/src/mocks/handlers/index.ts
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/goalRoom/remote.ts
[CK-95](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-95)
- msw 오류 해결
- 사실 왜 해결되었는지 정확히는 잘 모르겠지만, index.tsx 에서 msw 구동 방식을 조금 바꿔봤습니다. 제 로컬에서는 정상작동!
- 골룸 단일 조회 mocking fixture 생성 및 handler 연결
- 골룸 단일 조회 fetching hook 구현 
- 골룸 단일 조회 상단 header 에 데이터 매핑
- 코드를 보며 얘기해보고 싶은 부분이 있어 files changed 에 코멘트로 달아놓겠습니다! 확인 부탁드려용
- 골룸 상단부분 데이터 매핑
> [feat/CK-95] 골룸 상단부분 데이터를 매핑한다

- client/src/apis/axios/client.ts
- client/src/apis/user.ts
- client/src/components/signUpPage/SignUpForm.tsx
- client/src/myTypes/user/remote.ts
- client/webpack.prod.js
> [feat/CK-123] 로그인 서버 연결 및 웹팩 설정을 변경한다

- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
- client/src/components/icons/svgIcons.tsx
- client/src/hooks/_common/useHover.ts
- client/src/mocks/fixtures/goalRoom.ts
- client/src/styles/animations.ts
[CK-97](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-97)
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81363031/bc1eadc6-10e4-4bfd-9eac-10bb90643a8e
- 투두리스트 스타일링
- 투두리스트 데이터 매핑
잘 부탁 드립니다~~
- 투두리스트 데이터 매핑
> [feat/CK-97] 투두리스트 조회 데이터 매핑 및 스타일링

- client/src/components/_common/dialog/dialog.tsx
- client/src/components/mainPage/MainPage.tsx
- client/src/context/dialogContext.ts
- client/src/myTypes/_common/dialog.ts
CK-101
- compound 패턴으로 dialog 추상화 했습니다. 엄청엄청 약식 추상화여서 지금 간단하게 쓸 수 있어요 (추후 수정 꼭 할게요!)
- @/components/_common/mainpage 에 사용방식을 적어놓고 적용시켜놨어요. 실행시키면 메인페이지에 바로 뜰거에요 사용하고  지워주심 됩니다~
> [feat/CK-101] 모달을 약식 추상화한다

- client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.styles.ts
- client/src/mocks/fixtures/goalRoom.ts
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/goalRoom/remote.ts
CK-126
develop-client 빌드 오류 해결했습니다
> [Feat/CK-126] develop-client 빌드 오류를 해결한다

- client/src/apis/axios/client.ts
- client/src/apis/roadmap.ts
- client/src/components/roadmapCreatePage/difficulty/difficulty.styles.ts
- client/src/components/roadmapCreatePage/mainText/MainText.tsx
- client/src/components/roadmapCreatePage/roadmap/Roadmap.tsx
- client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
- client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
- client/src/components/roadmapCreatePage/roadmapCreateForm/roadmapCreateForm.styles.ts
- client/src/components/roadmapCreatePage/selector/SelectBox.tsx
- client/src/components/roadmapCreatePage/tag/Tag.tsx
- client/src/hooks/queries/roadmap.ts
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/hooks/roadmap/useCreateTag.ts
- client/src/myTypes/roadmap/remote.ts
CK-45
- 로드맵 생성 api 연동했습니다.
- 제목 & 소개글 & 난이도 & 기간 & 로드맵 은 필수고, 본문은 선택 입력사항이에요!
> [feat/CK-45] 로드맵 생성 api를 연결한다

- client/src/App.tsx
- client/src/apis/goalRoom.ts
- client/src/apis/roadmap.ts
- client/src/components/loginPage/loginForm/LoginForm.tsx
- client/src/hooks/queries/goalRoom.ts
- client/src/hooks/queries/roadmap.ts
- client/src/hooks/queries/user.ts
> [feat/CK-129] 오류해결 & 통합한다

- client/src/apis/goalRoom.ts
- client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
- client/src/hooks/queries/goalRoom.ts
- client/src/index.tsx
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/goalRoom/remote.ts
- client/src/pages/goalRoomListPage/GoalRoomListPage.tsx
> feat: 통신 에러 해결

- client/src/components/roadmapCreatePage/difficulty/Difficulty.tsx
- client/src/components/roadmapCreatePage/difficulty/difficulty.styles.ts
- client/src/components/roadmapCreatePage/selector/SelectBox.tsx
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/myTypes/_common/select.ts
CK-151
SelectBox 컴포넌트의 부족한 부분들을 수정했습니다.
- Option의 넓이를 수정해서 select박스의 어느부분도 클릭할 수 있게 만들었습니다.
- Select.Value를 만들어서 select박스에서 선택한 옵션이 trigger버튼 안에 표시될 수 있게 만들었어요.
너무 부족하다고 생각해서 계속 리뷰를 미뤘는데... 일단 리뷰 요청을 해야겠네요..!! 잘부탁드립니다~!
> [feat/CK-151] Selectbox의 오류를 해결한다

- client/src/apis/roadmap.ts
- client/src/components/icons/svgIcons.tsx
- client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
- client/src/components/roadmapCreatePage/roadmap/roadmap.styles.ts
- client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
- client/src/components/roadmapCreatePage/roadmapCreateForm/roadmapCreateForm.styles.ts
- client/src/hooks/_common/useUploadImage.ts
- client/src/hooks/queries/roadmap.ts
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/myTypes/roadmap/internal.ts
- client/src/myTypes/roadmap/remote.ts
CK-168
- 로드맵 생성부분에 사진을 추가할 수 있게 api가 변경되어서 수정했습니다. application-json 이 아니고 formData 형식이에요
- 코드가 아주 맘에 안들어유.. 관심사의 분리가 안된 느낌입니다잉 잘부탁드려요!
> [feat/CK-168] 로드맵 생성부분의 변경된 api를 반영한다 ( 사진추가 기능 )

- client/src/components/_common/navBar/NavBar.styles.ts
- client/src/components/_common/navBar/NavBar.tsx
- client/src/components/_common/pageLayout/PageLayout.styles.ts
- client/src/components/_common/pageLayout/PageLayout.tsx
- client/src/hooks/queries/user.ts
CK-164
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81363031/d94cb603-1613-4eec-88cd-ca5887014342
- 종종 네브바가 컨텐츠 뒤에 위치했던 버그
- 네브바가 작고 왼쪽에 치우쳐저 있다는 백엔드분들 피드백
- 네브바에 로그아웃 버튼 및 로직 (로그인 시)
이렇게 3개 작업했습니다!
잘 부탁드립니다~~~!!!
- navbar 재 스타일링
-로그아웃 기능 구현 및 적용
> [feat/CK-164] 네브바 고도화 및 로그아웃 버튼을 활성화한다

- client/.eslintrc.cjs
- client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
- client/src/components/goalRoomCreatePage/createGoalRoomForm/createGoalRoomValidations.ts
- client/src/constants/goalRoom/goalRoomValidation.ts
- client/src/hooks/_common/useFormInput.ts
ck-177
- Common
- Start Date
- End Date
잘 부탁드립니다!!
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/17e3defa-3d10-4d28-80a8-4dcac347ec08
> [feat/CK-177] 골룸 생성 유효성 검사를 고도화한다

- client/src/apis/roadmap.ts
- client/src/components/roadmapCreatePage/selector/SelectBox.tsx
- client/src/components/roadmapListPage/categories/Categories.tsx
- client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
- client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
- client/src/components/roadmapListPage/roadmapSearch/RoadmapSearchResult.tsx
- client/src/components/roadmapListPage/roadmapSearch/roadmapSearch.styles.ts
- client/src/hooks/queries/roadmap.ts
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/myTypes/_common/select.ts
CK-157
- 드디어 로드맵 검색기능 구현했습니다 미루고 미뤄서 죄송합니다~ㅇㅅㅇ
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/87578512/d387ddaa-0a8f-4469-80c3-eb6d2544b449
- 작업과정에서 카테고리를 선택할 때에는 query string을 활용하고, 검색결과를 볼 때는 url의 그냥 파라미터를 이용했어요. 쓰레기코드인걸 알지만.. 로드맵 리스트 전체 구조를 바꾸기에는 시간이 없어서 일단 돌아가는대로 코드를 작성했습니다. 빠른 시일내에 리팩토링 진행할께요!!
> [feat/CK-157] 로드맵 리스트의 검색기능을 구현한다

- backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/RoadmapAPIFixture.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
> [Release] CK Backend v1.1.1

- backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/RoadmapAPIFixture.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
> [Release] CK Backend v1.1.2

- client/src/constants/roadmap/category.ts
> [Release] CK Frontend v1.0.2

- client/src/components/_common/toolTip/ToolTip.styles.ts
- client/src/components/_common/toolTip/ToolTip.tsx
CK-185
잘 부탁드립니다!!
- 사용자에게 부가적인 설명을 전하기 위한 Tool Tip 컴포넌트 구현
```jsx
<ToolTip>
이와 같이 설명 글을 넣어줍니다. <strong>강조</strong>하고 싶은
글에는 이와 같이 <strong>strong 태그</strong>로 감싸줍니다.
</ToolTip>
```
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/c8a7615f-675d-43fe-a9c4-6c97b9b9e08e
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/2cb88a35-6cdd-446a-95b7-dc86f25bb0a3
> [feat/CK-185] 툴팁(Tool Tip)을 구현한다

- client/src/components/_common/InputField/InputField.styles.ts
- client/src/components/_common/InputField/InputField.tsx
- client/src/components/_common/toolTip/ToolTip.styles.ts
- client/src/components/_common/toolTip/ToolTip.tsx
- client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
- client/src/components/goalRoomCreatePage/nodeSection/NodeSection.tsx
- client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
CK-193
- 인증 횟수에 툴팁 적용
- 오타 수정
- 일증 횟수 -> 인증 횟수
슬랙에 공유하고 툴팁 컴포넌트의 스타일을 조금 수정했습니다
잘 부탁드립니다!
> [feat/CK-193] 인증 횟수에 툴팁을 적용하고 오타를 수정한다

- client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
- client/src/components/_common/roadmapItem/RoadmapItem.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
- client/src/components/myPage/myPageContent/MyPageContent.tsx
- client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.tsx
- client/src/components/roadmapDetailPage/roadmapNodeList/RoadmapNodeList.tsx
- client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
- client/src/index.tsx
> [feat/CK-197] 릴리즈 전 최종 QA 반영

- client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
- client/src/components/roadmapListPage/roadmapSearch/NoResult.tsx
- client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
- client/src/components/roadmapListPage/roadmapSearch/RoadmapSearchResult.tsx
- client/src/components/roadmapListPage/roadmapSearch/roadmapSearch.styles.ts
CK-213
로드맵 검색부분 오류 수정했습니다
- 검색어가 없을 때 검색버튼 누르면 뻑가는 오류 수정
- 엔터키로 검색 가능
- 검색결과 초기화 할 때 검색창도 초기화 로직 추가
잘부탁드림당~
> [feat/CK-213] 로드맵 검색 오류를 해결한다.

- client/src/styles/GlobalStyle.tsx
> [hotfix/CK-214] 개행 문자에 대한 개행이 이루어지지 않던 문제 해결

- client/src/components/_common/slider/Slider.styles.ts
CK-214 -> hotfix파서 했습니다
article 부분의 너비를 100%로 수정했습니다.
> [hotfix/CK-214] slider의 너비가 줄어들지 않는 오류를 해결한다.

- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.styles.ts
CK-215
S.TodoContent의 text-overflow 속성 제거
> [hotfix/CK-215] 투두 컨텐츠에 스크롤이 가능하도록 변경한다

- client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
- client/src/components/_common/roadmapItem/RoadmapItem.tsx
- client/src/components/roadmapListPage/categories/Categories.styles.ts
- client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
- client/src/components/roadmapListPage/roadmapListView/RoadmapListView.styles.ts
- client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
- client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
- client/src/components/roadmapListPage/roadmapSearch/roadmapSearch.styles.ts
- client/src/styles/GlobalStyle.tsx
CK-218
로드맵 리스트 페이지 모바일 대응했습니다.
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/87578512/d712998e-e50d-4576-ad08-45183a5fd569
> [feat/CK-218] 로드맵 리스트 페이지 모바일 대응을 한다.

- client/src/components/roadmapCreatePage/category/category.styles.ts
CK-219 
로드맵 생성페이지 모바일 대응입니다.
화면이 줄어들 때 카테고리 줄바꿈하는것 밖에 없어서 변경사항은 거의 없어요!
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/87578512/7a867db8-9dc3-48f9-a1b5-3c7cf9fd4e6d
> [feat/CK-219] 로드맵 생성 페이지 모바일 대응을 한다. 

- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
CK-217
대시보드 모바일 대응했습니다!
대시보드 로드맵에 전체 로드맵을 볼 수 있도록 모달을 달아주었습니다!
잘 부탁드림다
- 대시보드 모바일 대응
- 대시보드 로드맵 모달 구현
> [feat/CK-217] 골룸 목록 조회 페지이의 모바일 대응 및 로드맵 모달을 구현한다.

- client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
- client/src/styles/GlobalStyle.tsx
CK-221
- 골룸 목록 조회 모바일 대응
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/c148f6fe-fb2f-4e74-9813-150cdd223617
잘 부탁드립니다~!!
> [feat/CK-221] 골룸 목록 조회 페지이의 모바일 대응을 한다.

- client/src/components/_common/navBar/NavBar.styles.ts
CK-224
- 모바일 환경에서 로그인 버튼이 보이지 않는 문제 해결
- 코끼리끼리 로고에 padding-top 적용
- stylelint가 적용되지 않은 부분 수정
잘 부탁드려요~~!
- 네브바 모바일 대응
> [feat/CK-224] 네브바의 모바일 대응을 수행한다
