woowacourse-teams/2023-co-kirikiri

- client/src/components/_common/pageLayout/PageLayout.styles.ts
- client/src/components/_common/pageLayout/PageLayout.tsx
- client/src/components/_common/responsiveContainer/ResponsiveContainer.styles.tsx
- client/src/utils/_common/pxToVw.ts
53
https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-53
Web 환경에서 width이 1137px이 되도록,
모바일과 테블릿 환경에서 100vw가 되도록 변경
PageLayout 템플릿 추가
반응형 레이아웃의 요구 사항이 변하면서 `pxToVw`함수의 필요성을 느끼지 못했습니다
이러한 이유로 제거하였는데 혹시 다른 고견이 있으시다면 말씀해주시면 감사드리겠습니다!!
또 PageLayout을 추가하였습니다
Header(NavBar), Footer 등을 추가하기 위해서 입니다
반응형 Layout과는 성격이 다르다고 생각해서 따로 분리했습니다! 이것도 의견 부탁드려요!
추후, props를 넘겨서 page 마다 다르게 대응할 수 있도록 유연하게 수정할 예정입니다!
> [feat/CK-53] 반응형 Layout의 변경된 요구사항을 반영하고 PageLayout을 구현한다

- client/src/components/_common/button/Button.tsx
- client/src/components/roadmapCreatePage/category/category.tsx
- client/src/components/roadmapCreatePage/difficulty/difficulty.tsx
https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1/backlog?selectedIssue=CK-104
깃 캐시 에러 해결
ButtonProps에 옵셔널이 적용되지 않았던 이슈 해결
> [feat/CK-104] develop-client에 발생한 에러를 해결한다

- client/webpack.common.js
- client/webpack.prod.js
[CK-111](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-111)
- develop-client 에서 build 시 에러가 나는 문제를 해결했습니다.
- image-webpack-loader, OptimizeCSSAssetsPlugin 사용을 멈추게끔 작업했습니다.
- 정상적으로 build 되는 상황 확인 완료. 
잘부탁드려요~~~ 🙇‍♂️
- webpack image-webpack-loader, OptimizeCSSAssetsPlugin 관련 build error를 해결
> [feat/CK-111] webpack image-webpack-loader, OptimizeCSSAssetsPlugin 관련 build error를 해결한다.

- client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
- client/src/components/roadmapCreatePage/tag/Tag.tsx
- client/src/components/roadmapCreatePage/tag/TagItem.tsx
- client/src/components/roadmapCreatePage/tag/tag.styles.ts
- client/src/constants/roadmap/regex.ts
- client/src/constants/roadmap/tag.ts
- client/src/hooks/_common/useValidateInput.ts
- client/src/hooks/roadmap/useCreateTag.ts
- client/src/index.tsx
[CK-86](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1/backlog?selectedIssue=CK-86)
- 태그를 생성하는 부분을 구현했습니다.
- 이부분은 textarea가 아니라 input태그를 이용해야해서 이전에 만들어뒀던 input컴포넌트를 재화용하지 못했어요.. 이전에 만들어뒀던 공용컴포넌트 & input로직을 전체적으로 수정해야할 것 같아요😭
- 태그는 10자 이하로 입력할 수 있고, 전체 개수는 5개까지 생성할 수 있습니다.
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/87578512/35656f10-a5b0-4864-acd3-1392f1f116d1
- 화면 전체적으로 리랜더링이 될 때 높이가 달라져서 화면이 이리저리 흔들리는 현상이 생기는데.. 아직 이유를 못찾았습니다ㅠ
- 작업 속도가 느려서 죄송해욤.. 빠르게 하겠슴당 화이팅!
> [feat/CK-86] 로드맵의 태그를 생성한다

- backend/kirikiri/src/main/java/co/kirikiri/domain/ImageDirType.java
- backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
- backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
- backend/kirikiri/src/main/java/co/kirikiri/service/FilePathRandomGenerator.java
- backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
- backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
- backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
- backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
[CK-133](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-133)
- 참가한 골룸이 시작하지 않았을 때 사용자 골룸 단일 조회 시 인증 피드를 받아오지 못해 발생한 버그 해결
- `GoalRoomReadIntegrationTest`에서 사용자 골룸 단일/목록 조회 테스트 누락 복원
- 인증 피드 추가 메서드와 `getGoalRoomNodeByDate`를 공유해서 생긴 버그. 예외 처리를 도메인에서 하는 것이 아닌 Optional로 포장해서 서비스까지 넘긴 뒤에 메서드에서 처리했습니다.
- 일단 먼저 죄송합니다. 버그 수정 작업 중 찾았는데 사용자 골룸 단일/목록 조회 기능을 merge conflict 하면서 통합 테스트에서 누락한 걸 발견했습니다. 😱 아마 UI 창에서 하다 merge theirs와 같은 버튼을 눌렀던 것이 아닐까 생각합니다. 다른 테스트 부분들도 호다닥 살펴봤지만 엄청나게 삭제가 된 부분은 다행이 없었습니다. 다음부턴 더 주의하도록 하겠습니다. 😥😥 해당 부분은 [여기](https://github.com/woowacourse-teams/2023-co-kirikiri/pull/48/commits/26d7c7292aa66fc6cbacbd4cbb477bfb353c392b#diff-d98c5c388149e521b53d6afbcff72182af8ab83cb057fdd08503532a3a31d562)서 확인하실 수 있습니다.
- 사용자가 참가한 골룸이 시작하기 전이라도 단일 페이지를 조회할 …
> fix: 시작하지 않은 골룸 페이지 진입 시 인증 피드를 받아오지 못하는 버그 수정 및 사용자 골룸 조회 테스트 복원

- client/src/App.tsx
- client/src/apis/goalRoom.ts
- client/src/apis/user.ts
- client/src/components/_common/navBar/NavBar.styles.ts
- client/src/components/_common/navBar/NavBar.tsx
- client/src/components/_common/roadmapItem/RoadmapItem.tsx
- client/src/components/_common/toastProvider/ToastProvider.tsx
- client/src/components/_providers/UserInfoProvider.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/loginPage/loginOptions/LoginOptions.tsx
- client/src/components/roadmapListPage/categories/Categories.styles.ts
- client/src/components/roadmapListPage/categories/Categories.tsx
- client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
- client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
- client/src/components/signUpPage/SignUpForm.tsx
- client/src/hooks/queries/goalRoom.ts
- client/src/hooks/queries/user.ts
- client/src/hooks/roadmap/useSelectCategory.ts
- client/src/hooks/user/useValidationCheck.ts
- client/src/mocks/fixtures/goalRoom.ts
- client/src/myTypes/_common/user.ts
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/goalRoom/remote.ts
- client/src/myTypes/user/remote.ts
- client/src/pages/myPage/MyPage.tsx
- client/src/tests/utilTests/isValidUserInfo.test.ts
- client/src/utils/user/isValidUserInfo.ts
[CK-132](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-132)
- 팀원분들이 로그인했는지 모르겠다는 피드백을 받아 로그인 성공 시 유저 정보를 받아 전역 컨텍스트에 저장 후 네브바에 도출했습닏다.
- 로그인 성공시 연속적으로 유저 정보 받는 api 요청을 통해 받은 response 를 전역에 저장했습니다.
- nav 컴포넌트에서 리렌더시마다 유저 정보가 아직 유효한지 검증 후 아니라면 로그아웃 처리를 합니다.
- 로그인 성공 시 토스트 메세지를 도출합니다.
-  구현이 되어있지 않은 소셜 로그인 버튼을 주석처리하였습니다.
- 투두리스트에 완료되었는지 여부를 판단하는 필드와 변경할 수 있는 api 가 추가되어 이에 대응하는 코드를 작성했습니다.
- 로드맵 리스트 페이지의 웹 접근성을 대폭 향상하여 screen reader 사용 시 각 요소와 텍스트가 무엇을 뜻하는지 알 수 있도록 처리하였습니다. 
잘 부탁드립니다!
- 유저 auth 관련 통신 에러 해결 
- 투두리스트 변경점 대응
- 웹 접근성 향상
> [feat/CK-132] 각종 통신 에러 해결 및 투두리스트 변경점 대응 및 웹 접근성 향상

- backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
[CK-133](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-133)
- 참가한 골룸이 시작하지 않았을 때 사용자 골룸 단일 조회 시 인증 피드를 받아오지 못해 발생한 버그 해결
- 인증 피드 추가 메서드와 `getGoalRoomNodeByDate`를 공유해서 생긴 버그. 예외 처리를 도메인에서 하는 것이 아닌 Optional로 포장해서 서비스까지 넘긴 뒤에 메서드에서 처리했습니다.
- 사용자가 참가한 골룸이 시작하기 전이라도 단일 페이지를 조회할 수 있도록 수정한다
> fix: 사용자 골룸 단일 조회 버그 fix

- client/src/apis/goalRoom.ts
- client/src/apis/roadmap.ts
- client/src/components/_common/button/Button.tsx
- client/src/components/_common/dialog/dialog.tsx
- client/src/components/_common/roadmapItem/RoadmapItem.tsx
- client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
- client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
- client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialogContent.tsx
- client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
- client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
- client/src/components/roadmapCreatePage/roadmap/roadmap.styles.ts
- client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
- client/src/components/roadmapCreatePage/roadmapCreateForm/roadmapCreateForm.styles.ts
- client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
- client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
- client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
- client/src/hooks/queries/goalRoom.ts
- client/src/hooks/queries/roadmap.ts
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/mocks/fixtures/roadmapList.ts
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/goalRoom/remote.ts
- client/src/myTypes/roadmap/internal.ts
- client/src/myTypes/roadmap/remote.ts
CK-130
- 골룸 단일조회 UI
- 골룸 단일조회 서버연결
- 로드맵 목록조회 api로직 수정
- 로드맵 단일조회 서버연결
- 로드맵 생성페이지로 갈 수 있는 경로 생성
- 골룸 생성페이지로 갈 수 있는 경로 생성
- 그밖의 라우팅 처리
리팩토링 많이 필요해요
> [feat/CK-130] 페이지 라우팅과 잔여 서버 연결을 처리한다

- client/src/apis/goalRoom.ts
- client/src/components/_common/roadmapItem/RoadmapItem.tsx
- client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
- client/src/hooks/_common/useFormInput.ts
- client/src/hooks/queries/goalRoom.ts
[CK-140](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-140)
- 골룸 생성이 되지 않는 버그 해결 (useFormInput)
- 골룸을 생성하면 골룸 리스트 목록으로 리다이렉트 되도록 변경
현재까지는 골룸을 생성하고 목록으로 페이지를 이동시켜도 refetch가 이루어지진 않습니다
> [feat/CK-140] 골룸 생성이 되지 않는 버그를 해결한다

- .gitmodules
- backend/kirikiri/src/docs/asciidoc/goalroom.adoc
- backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
- backend/kirikiri/src/main/java/co/kirikiri/domain/BaseCreatedTimeEntity.java
- backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/CheckFeed.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepositoryImpl.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
- backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
- backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/CheckFeedResponse.java
- backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomCheckFeedResponse.java
- backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/response/MemberNameAndImageResponse.java
- backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
- backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
[CK-116](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-116)
- 골룸의 인증 피드를 전체 조회하는 기능을 구현했습니다.
- 구현하면서 크게 고민했던 부분이 없는것 같네요..! 간단한 기능이여서 금방 리뷰하실 수 있을 것 같아요!!
잘부탁드립니다🙇‍♀️
> [feat/CK-116] 골룸의 인증 피드를 전체 조회하는 기능을 구현한다

- client/src/apis/goalRoom.ts
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
- client/src/constants/@queryKeys/queryKeys.ts
- client/src/hooks/queries/goalRoom.ts
- client/src/myTypes/goalRoom/remote.ts
[CK-149](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-149)
- 인증피드 도출 로직 구현
- 골룸 인증피드 컴포넌트에 인증피드 전체 렌더링
잘부탁드립니다.
- 골룸 인증피드 내부 전체 인증피드 도출 로직 구현
> [feat/CK-149] 골룸 인증피드 내부 전체 인증피드 도출 로직을 구현한다

- client/src/apis/goalRoom.ts
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
- client/src/constants/goalRoom/goalRoomFilter.ts
- client/src/hooks/queries/goalRoom.ts
- client/src/myTypes/_common/global.d.ts
- client/src/myTypes/goalRoom/remote.ts
CK-156
골룸 리스트에 있는 버그들 & 부족한 부분들을 해결했습니다.
- 골룸 리스트 필터링 기능 구현
- 무한스크롤이 적용된 api명세 반영
selectBox컴포넌트를 활용해서 골룸 리스트의 필터 컴포넌트를 만든 뒤 render-props를 이용해서 그 안에 상태를 꺼내는 방식으로
골룸리스트를 필터링해줬습니다.
```ts
const GoalRoomFilter = ({
children,
}: {
children: (
selectedOption: (typeof goalRoomFilter)[keyof typeof goalRoomFilter]
) => React.ReactNode;
}) => {
// logic
return (
<S.FilterWrapper>
<Select externalSelectState={selectFilterOption}>
<Select.Trigger asChild>
<S.FilterTrigger>{selectedOption}</S.FilterTrigger>
</Select.Trigger>
{children(selectedOption)}
</Select>
</S.FilterWrapper>
);
};
```
이런 식으로 GoalRoomFilter컴포넌트는 `children함수`를 반환해요.
```ts
<GoalRoomFilter>
{(selectedOption) => {
setSortedOption(selectedOption);
return (
<Select.OptionGroup asChild>
<S.FilterOptionWrapper>
<Select.Option id={1} …
```
> [feat/CK-151] 골룸리스트의 오류를 해결한다

- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberQueryRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberQueryRepositoryImpl.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
- backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
- backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
[CK-165](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1/backlog?selectedIssue=CK-165)
- 골룸 참여자 조회 시 골룸이 진행중이거나 완료됐을 때만 조회가 가능한 로직을 모집중일 때도 조회가능하도록 수정했습니다.
- 제가 머지하면서 브랜치가 이상하게 꼬여서 브랜치 삭제하고 다시 추가했어요ㅠㅠ!
> [Fix/CK-165] 골룸 참여자 조회 시 골룸의 상태에 상관없이 조회 가능하도록 수정한다

- client/src/components/loginPage/loginContent/LoginContent.styles.ts
- client/src/components/loginPage/loginContent/LoginContent.tsx
- client/src/components/loginPage/loginForm/LoginForm.tsx
- client/src/hooks/queries/user.ts
CK-163
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81363031/65d33721-ec0c-43a8-a771-b49da03920e7
- 기존 로그인 폼과 비교해 사이즈 크게 잡았습니다.
- 기존 버튼과 로고가 겹치는 상황 해결
- 기존 그냥 로그인 버튼 누르면 홈으로 가던 로직에서 `성공해야` 홈으로 가게끔 라우팅 처리
자아아알~ 부탁드립니다!
- 로그인 폼 스타일링 고도화
- 로그인 폼 네비게이팅 로직 개선
> [feat/CK-163] 로그인 라우팅 처리 로직 수정 및 뒤로가기 버튼 위치를 조정한다

- client/src/apis/goalRoom.ts
- client/src/components/_common/wavyLoading/WavyLoading.styles.ts
- client/src/components/_common/wavyLoading/WavyLoading.tsx
- client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
- client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
- client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
- client/src/constants/@queryKeys/queryKeys.ts
- client/src/hooks/queries/goalRoom.ts
- client/src/myTypes/goalRoom/remote.ts
- client/src/pages/goalRoomCreatePage/GoalRoomCreatePage.tsx
CK-166
잘 부탁드리겠습니다~!!!
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/4cd556e4-ac58-4059-ab55-e3d260655989
> [feat/CK-166] 골룸 리스트 페이지 버그 수정 및 무한 스크롤을 구현한다

- client/src/apis/goalRoom.ts
- client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
- client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
- client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
- client/src/components/roadmapCreatePage/selector/SelectBox.tsx
- client/src/constants/goalRoom/goalRoomFilter.ts
- client/src/myTypes/goalRoom/remote.ts
CK-172
잘 부탁드립니다~!
- 골룸 목록 정렬 API 변경사항 반영
- 골룸 목록 스타일 고도화
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/57d80665-ec38-4709-acad-b7475a834eef
> [feat/CK-172] 골룸 목록 정렬 구현 및 스타일 고도화를 진행한다

- backend/kirikiri/src/docs/asciidoc/roadmap.adoc
- backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
- backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapCategory.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapCategoryRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
- backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/request/RoadmapCategorySaveRequest.java
- backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
- backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
- backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapCategoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadOrderIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/RoadmapAPIFixture.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/helper/InitIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestConfig.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestTransactionService.java
- backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapCreateServiceTest.java
[CK-179](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1/backlog?selectedIssue=CK-179)
로드맵 카테고리 생성 API를 구현 했습니다.
인수테스트에서 기존에 로드맵 카테고리 생성 부분을 API를 사용하도록 교체 했습니다.
밀리가 작업하시는 ADMIIN 추가 후에 controller에서 ADMIN 계정만 사용할 수 있게 수정해야합니다!
> [feat/CK-179] 로드맵 카테고리 생성을 구현한다

- client/src/apis/axios/client.ts
- client/src/components/_common/toolTip/ToolTip.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
- client/src/hooks/queries/goalRoom.ts
- client/src/styles/theme.ts
CK-192
- 인증피드 모달 내부 스크롤 구현 
- 투두리스트 등록 시 invalidation 처리 정상화
- 골룸 항목들 (투두리스트, 인증피드) 전체 개수 표기 제거
- 툴팁 적용
잘 부탁드립니다!
- 인증피드 모달 내부 스크롤 구현 
- 투두리스트 등록 시 invalidation 처리 정상화
- 골룸 항목들 (투두리스트, 인증피드) 전체 개수 표기 제거
- 툴팁 적용
> [feat/CK-192] 툴팁 적용 및 골룸 개선

- client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
CK-195
- 노드 목록의 컨텐츠를 한번에 보여주는 것으로 가시성을 향상한다
잘 부탁드립니다!!
- 노드 목록의 가시성 향상
> [feat/CK-195] 노드 목록의 가시성 향상한다

- client/src/App.tsx
- client/src/apis/axios/client.ts
- client/src/components/_common/sessionHandler/SessionHandler.tsx
CK-198
- 기존 `refresh token` 만료시 무한 reissue 가 요청되는 버그를 수정했습니다.
- refresh token 만료시 501 에러가 특정한 에러 메세지와 함께 응답으로 와 에러 바운더리에 걸렸기에, 이를 우회해서 해당 상황에 error 를 throw 하지 않도록 구현했습니다.
잘 부탁드립니다!!!
- token reissue 에러 핸들링 및 
- session Handler wrapper component 구현
> [feat/CK-198] token reissue 에러 핸들링 및 session Handler wrapper component 구현

- client/src/components/_providers/UserInfoProvider.tsx
- client/src/components/myPage/myPageUserInfo/MyPageUserInfo.tsx
- client/src/hooks/_common/useIdentifyUser.ts
- client/src/myTypes/user/remote.ts
- client/src/tests/utilTests/isValidUserInfo.test.ts
ck-208
- `/me` response type 에 이메일 필드를 추가했습니다!
- 마이 페이지에 이메일을 도출 할 수 있도록 했습니다!
잘 부탁드려요~
- `/me` response type 에 이메일 필드 추가
- 마이 페이지에 이메일을 도출
> [hotfix/CK-208] 마이 페이지에 이메일을 도출한다

- client/src/components/roadmapCreatePage/difficulty/Difficulty.tsx
- client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
- client/src/components/roadmapCreatePage/tag/Tag.tsx
- client/src/constants/roadmap/tag.ts
- client/src/hooks/roadmap/useCollectRoadmapData.ts
- client/src/hooks/roadmap/useCreateTag.ts
- client/src/myTypes/roadmap/internal.ts
CK-212
로드맵 생성페이지 오류 해결했습니다.
- 요청이 잘못되었을 때 다시 요청보낼 수 없는 오류 해결
- 난이도 요청 잘못가는 오류 해결
- 태그 무한생성오류 해결
- 중복되는 태그가 생성되는 오류 해결
- 로드맵의 첫번째 노드 기본으로 노출시킴
잘부탁드림당~
> [feat/CK-212] 로드맵 생성페이지 오류를 해결한다.

- client/src/App.tsx
- client/src/components/_common/privateRouter/PrivateRouter.tsx
CK-209
-  기존 로그인 시 `/me` 요청을 통해 나라는 유저의 정보를 가져오쥬? 그리고 받아온 정보를 전역 컨텍스트에 저장 후 지속적으로 사용합니다.
허나 문제는 새로고침 시 전역 컨텍스트에 저장되어 있는 나라는 유저의 정보가 초기화가 되기에, 미리 가지고 있던 accessToken 을 사용하여 다시 유저 정보를 가져온다 해도 가져오기 전 빈 시간동안은 유저 정보가 없게 됩니다. 그 시점에, 유저가 private router(유저가 로그인 되어있는지 체크) 로 감싸진 위치에 있다면 강제적으로 로그인 페이지로 이동하게 되었던 상황임다.
- 그래서 throttle 이나 debounce 를 걸어 시간을 벌어야 할지, 고민 중 성공은 했으나, 정확한 조건을 정의할 수 없었고 성공률이 100퍼센트는 아니라고 생각했기에, 단순 유저가 로그인 되어있는지 확인하는 로직에 accessToken 까지 체크하는 로직을 넣어 다시 유저 정보를 불러올 수 있는 시간을 벌 수 있게 했슴다.
잘 부탁드려요!
- 새로고침 시 로그인 페이지로 강제 이동하는 버그 픽스
> [feat/CK-209] 새로고침 시 로그인 페이지로 이동하는 버그를 해결한다.

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/_common/routeChangeTracker/RouteChangeTracker.tsx
- client/webpack.common.js
ck-211
- GA 를 RouteChangeTracker 컴포넌트를 구현 후  적용했습니다!
잘 부탁드려용~
- GA 적용
> [feat/CK-211] Google Analytics 를 적용한다.

- client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
- client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.tsx
- client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
- client/src/myTypes/goalRoom/internal.ts
- client/src/myTypes/roadmap/internal.ts
CK-228
- roadmapContentId와 roadmapId가 명확히 구분되어 있지 않던 것 수정
- 대시보드에서 로드맵 디테일 정보 전체가 아닌 노드 리스트를 요청하도록 수정
잘 부탁드립니다~!
> [feat/CK-228] 골룸 관련 API를 동기화한다.

- backend/kirikiri/src/main/java/co/kirikiri/common/resolver/MemberIdentifierArgumentResolver.java
- backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
- backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
- backend/kirikiri/src/test/java/co/kirikiri/common/resolver/MemberIdentifierArgumentResolverTest.java
[CK-231](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-231)
- `@MemberIdentifier`를 사용하려면 `@Authenticated`를 사용하도록 강제했습니다.
- 몹프로그래밍👨‍👩‍👦
> [feat/CK-231] 인증/ 인가 시 @MemberIdentifier를 @Authenticated와 함께 사용하도록 수정한다

- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberDao.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberJdbcRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberJdbcRepositoryImpl.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
- backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomRepository.java
- backend/kirikiri/src/main/java/co/kirikiri/service/scheduler/GoalRoomScheduler.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomSchedulerIntegrationTest.java
- backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestTransactionService.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomToDoCheckRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
- backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomSchedulerTest.java
[CK-236](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-236)
- 기존 골룸 시작 시 골룸 대기자에서 참여자로 변경되는 시점에 데이터 삽입, 삭제를 jdbcTemplate을 이용하여 bulk insert를 적용했습니다.
- JPA에서 saveAll, deleteAll은 내부적으로 데이터 하나씩 쿼리가 나가기 때문에, 이를 개선하고자 JdbcTemplate을 사용해서 bulk insert를 적용했습니다.
- JPA에서는 id 전략이 Identity이면 bulk insert가 지원이 안되고, Sequence나 Table 전략을 사용해야 가능합니다. 하지만 MySql은 Sequence를 지원하지 않고, Table 전략을 채택하기에는 테이블을 추가해야하는 점에서 부담이 되어 Identity 전략을 그대로 가되, JdbcTemplate을 사용하여 bulk insert를 적용하도록 했습니다.
- 추가적으로, 로드맵 삭제 시 관련 데이터들이 모두 삭제되는데 이 부분도 단 건씩 삭제되어 개선이 필요합니다! 로드맵 삭제 부분은 비교적 중요한 부분이 아니고, 쿼리만 추가해주면 되기 때문에 바쁜 일정이 끝나는대로 수정해보겠습니다 🥲
> [feat/CK-236] JdbcTemplate을 이용하여 bulk insert를 적용한다
